name: Tests

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run tests
        run: make test
        if: env.GIT_DIFF
  code_cov:
    name: Cover report
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        envs: ["stable-codecov"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run stable test cover
        if: matrix.envs == 'stable-codecov'
        run: make test-cover
      - name: Upload codecov report
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: ${{matrix.envs}}
          file: coverage.txt
